better interactive checkout

diff --git a/bin/git-checkout-interactive b/bin/git-checkout-interactive
--- a/bin/git-checkout-interactive
+++ b/bin/git-checkout-interactive
@@ -1,25 +1,23 @@
+#!/usr/bin/env bash
+
 set -e
 
-COUNTER=1
-BRANCHES=($(git branch --list | grep --regexp ^[^*]))
-INVALID="ERROR: invalid selection"
+counter=1
+branches=($(git for-each-ref --format='%(refname:short)' refs/heads/))
 
 echo "" # start with a newline
 
-for BRANCH in ${BRANCHES[@]}; do
-  echo "$COUNTER. $BRANCH"
-  let COUNTER+=1
+for name in ${branches[@]}; do
+  printf "%3s %s\n" "$counter." "$name"
+  let counter+=1
 done
 
 echo -ne "\nWhich branch number? "
-read NUM
+read n
 
-if [ $NUM -lt 1 ]; then
-  echo $INVALID
-  exit 1
-elif [ $NUM -gt ${#BRANCHES[@]} ]; then
-  echo $INVALID
-  exit 1
+if [[ $n =~ ^[0-9]+$ && $n -ge 1 && $n -le ${#branches[@]} ]]; then
+  git checkout ${branches[n-1]}
 else
-  git checkout ${BRANCHES[NUM-1]}
+  echo "Invalid selection!"
+  exit 1
 fi
